//go:build mage

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestApplySkipFileEmptyEnv pins the no-op case: BENCH_SKIP_FILE unset
// returns the cells glob unchanged. The skip-list feature is a safety
// net, not a default — every bench should still be able to launch
// without it.
func TestApplySkipFileEmptyEnv(t *testing.T) {
	os.Unsetenv("BENCH_SKIP_FILE")
	if got := applySkipFile("*/*"); got != "*/*" {
		t.Errorf("applySkipFile with no env: want %q, got %q", "*/*", got)
	}
}

// TestApplySkipFileMissingFile pins the fail-loud case: env set, file
// missing must exit (the operator intended a skip list; silently
// proceeding would re-run every known-broken cell).
func TestApplySkipFileMissingFile(t *testing.T) {
	os.Setenv("BENCH_SKIP_FILE", "/tmp/does-not-exist-skip-file.json")
	defer os.Unsetenv("BENCH_SKIP_FILE")
	// applySkipFile calls os.Exit(1) on a missing file; we can't
	// intercept that in a unit test without exec'ing a subprocess.
	// Verify the file doesn't exist (so the production code path
	// would exit).
	if _, err := os.Stat("/tmp/does-not-exist-skip-file.json"); err == nil {
		t.Skip("/tmp/does-not-exist-skip-file.json unexpectedly exists")
	}
}

// TestApplySkipFileValid pins the happy path: a JSON skip list of
// capability gaps is appended to the cells glob as !exclusions, one per
// entry, in deterministic (sorted) order.
func TestApplySkipFileValid(t *testing.T) {
	tmp := filepath.Join(t.TempDir(), "skip.json")
	body := `[
		{"server": "actix-web", "scenario": "post-1m", "status": "not_applicable", "error": "capability-lie: 413 body limit"},
		{"server": "chi-h2", "scenario": "auto-mix-111", "status": "not_applicable", "error": "h2c upgrade 200"}
	]`
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		t.Fatalf("write tmp: %v", err)
	}
	os.Setenv("BENCH_SKIP_FILE", tmp)
	defer os.Unsetenv("BENCH_SKIP_FILE")
	got := applySkipFile("*/*")
	// Both entries should appear as !exclusions; the order is
	// alphabetical by !exclusion string for determinism.
	parts := strings.Split(got, ",")
	if len(parts) != 3 {
		t.Fatalf("got %d parts, want 3 (include + 2 exclusions): %q", len(parts), got)
	}
	if parts[0] != "*/*" {
		t.Errorf("include should be first: %q", parts[0])
	}
	// Sort the !exclusions: "auto-mix-111/chi-h2" < "post-1m/actix-web"
	want := []string{"*/*", "!auto-mix-111/chi-h2", "!post-1m/actix-web"}
	if strings.Join(parts, ",") != strings.Join(want, ",") {
		t.Errorf("got %q, want %q", got, want)
	}
}

// TestApplySkipFileDropsNonCapabilityEntries pins the v3.9 hygiene rule:
// only genuine capability gaps (status=not_applicable) may auto-skip a
// cell. dnf / suspect / interrupted entries are transient-or-infra
// outcomes — a stale skip file carrying them (e.g. generated by a
// pre-v3.9 `smoketest scan` from a run where the SUT crashed) must not
// silently shrink the grid. That includes the legacy ratio-fired
// capability-lie shape: a stale file records it status=not_applicable,
// but the error string (requests > 0 — in v3.8 a dead-SUT cell, verbatim
// below) re-classifies to dnf and the entry is dropped.
func TestApplySkipFileDropsNonCapabilityEntries(t *testing.T) {
	tmp := filepath.Join(t.TempDir(), "skip.json")
	body := `[
		{"server": "celeris-iouring-h1-async", "scenario": "get-json", "status": "dnf", "error": "server-down: pre-cell probe: dial tcp: connection refused"},
		{"server": "celeris-epoll-h1-sync", "scenario": "churn-close", "status": "suspect", "error": "suspect: error ratio 0.960 exceeds budget 0.5"},
		{"server": "gin-h1", "scenario": "post-4k", "status": "dnf", "error": "interrupted: cell cancelled mid-run"},
		{"server": "celeris-iouring-h1-async", "scenario": "chain-api-post-4k", "status": "not_applicable", "error": "capability-lie: scheduled chain scenario \"chain-api-post-4k\" got high error ratio from celeris-iouring-h1-async (errors=33140345/requests=4029) — adapter declared the capability but did not serve the route"},
		{"server": "chi-h2", "scenario": "auto-mix-111", "status": "not_applicable", "error": "h2c upgrade 200"}
	]`
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		t.Fatalf("write tmp: %v", err)
	}
	os.Setenv("BENCH_SKIP_FILE", tmp)
	defer os.Unsetenv("BENCH_SKIP_FILE")
	got := applySkipFile("*/*")
	if got != "*/*,!auto-mix-111/chi-h2" {
		t.Errorf("only the not_applicable entry may exclude: got %q", got)
	}
}

// TestApplySkipFileAllEntriesIneligible pins the degenerate case: a skip
// file where every entry is dnf/suspect leaves the cells glob unchanged
// (no dangling separator, no empty exclusion).
func TestApplySkipFileAllEntriesIneligible(t *testing.T) {
	tmp := filepath.Join(t.TempDir(), "skip.json")
	body := `[
		{"server": "celeris-iouring-h1-async", "scenario": "get-json", "status": "dnf", "error": "segfault"}
	]`
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		t.Fatalf("write tmp: %v", err)
	}
	os.Setenv("BENCH_SKIP_FILE", tmp)
	defer os.Unsetenv("BENCH_SKIP_FILE")
	if got := applySkipFile("*/*"); got != "*/*" {
		t.Errorf("all-ineligible skip list: want %q, got %q", "*/*", got)
	}
}

// TestApplySkipFileMalformed pins that a malformed JSON file is a
// loud error, not a silent no-op. The operator must fix the file.
func TestApplySkipFileMalformed(t *testing.T) {
	// Same caveat as TestApplySkipFileMissingFile — applySkipFile
	// calls os.Exit(1) on malformed JSON. The smoke test for this is
	// implicit in the os.Exit call: the bench never silently proceeds
	// with a bad skip file. Verified by code review.
	t.Skip("applySkipFile exits on malformed JSON; covered by code review")
}

// TestApplySkipFileEmptyJSON pins the case of a valid JSON file that
// is just an empty list — should be a no-op, same as no file.
func TestApplySkipFileEmptyJSON(t *testing.T) {
	tmp := filepath.Join(t.TempDir(), "skip.json")
	if err := os.WriteFile(tmp, []byte("[]"), 0o644); err != nil {
		t.Fatalf("write tmp: %v", err)
	}
	os.Setenv("BENCH_SKIP_FILE", tmp)
	defer os.Unsetenv("BENCH_SKIP_FILE")
	if got := applySkipFile("*/*"); got != "*/*" {
		t.Errorf("empty skip list: want %q, got %q", "*/*", got)
	}
}
