package main

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// The corpus under testdata/*.out is REAL `go test -v` output of the sample
// module in testdata/samplemod, regenerated by testdata/regen.sh. These
// helpers wrap a body in the header and trailer shard.sh writes.

const testSHA = "0123456789abcdef0123456789abcdef01234567"

func sampleCase(name string) Case {
	return Case{
		Name: name, Packages: []string{"./a", "./b"}, Run: "", Count: 2, Shards: 1,
		Arches: []string{"x86"}, Memlock: "8m", Timeout: "5m",
		Flags: []string{}, Env: []string{}, Expect: Expect{Verdict: "PASS"},
	}
}

func corpus(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name+".out"))
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// headerFor is the header shard.sh would write for this shard; override
// replaces or (with an empty value in drop) removes keys.
func headerFor(c Case, arch string, shard int, override map[string]string) string {
	limit := memlocks[c.Memlock]
	machine := map[string]string{"x86": "x86_64", "arm64": "aarch64"}[arch]
	kv := [][2]string{
		{"case", c.Name}, {"arch", arch}, {"runner", runners[arch]}, {"shard", strconv.Itoa(shard)},
		{"shuffle", "4200" + strconv.Itoa(shard)}, {"celeris_ref", "main"}, {"celeris_sha", testSHA},
		{"expected_sha", testSHA}, {"memlock", c.Memlock}, {"memlock_limit", limit},
		{"memlock_default", "8388608:8388608"}, {"memlock_in_force", limit + ":" + limit}, {"race", strconv.FormatBool(c.Race)},
		{"count", strconv.Itoa(c.Count)}, {"timeout", c.Timeout}, {"run", c.Run},
		{"packages", strings.Join(c.Packages, " ")}, {"flags", strings.Join(c.Flags, " ")},
		{"env", strings.Join(c.Env, " ")}, {"machine", machine}, {"kernel", "6.11.0-test"},
		{"nproc", "4"}, {"image", "ubuntu24 20260907.300"}, {"go_version", "go version go1.27.0 linux/amd64"},
	}
	var b strings.Builder
	for _, p := range kv {
		v := p[1]
		if o, ok := override[p[0]]; ok {
			if o == "<drop>" {
				continue
			}
			v = o
		}
		b.WriteString("stress-header: " + p[0] + "=" + v + "\n")
	}
	b.WriteString("stress-header-end\n")
	return b.String()
}

func shardText(c Case, arch string, shard int, body, exit string, override map[string]string) string {
	s := headerFor(c, arch, shard, override) + body
	if exit != "" {
		if !strings.HasSuffix(s, "\n") {
			s += "\n"
		}
		s += "stress-trailer: exit=" + exit + " elapsed_s=3\n"
	}
	return s
}

func writeShard(t *testing.T, dir string, c Case, arch string, shard int, body, exit string, override map[string]string) {
	t.Helper()
	path := filepath.Join(dir, logName(c.Name, arch, shard))
	if err := os.WriteFile(path, []byte(shardText(c, arch, shard, body, exit, override)), 0o644); err != nil {
		t.Fatal(err)
	}
}

func row(t *testing.T, r CaseReport, pkg, name, arch string) TestRow {
	t.Helper()
	for _, x := range r.Tests {
		if x.Package == pkg && x.Name == name && x.Arch == arch {
			return x
		}
	}
	t.Fatalf("no row for %s %s %s", pkg, name, arch)
	return TestRow{}
}

func hasReason(reasons []string, r string) bool {
	for _, x := range reasons {
		if x == r || strings.HasPrefix(x, r+":") {
			return true
		}
	}
	return false
}
